server:
  port: 8081    #端口号

spring:
  application:
    name: web-service         #服务名
  datasource:                 #数据源配置
    url: jdbc:mysql://127.0.0.1:3306/jmyp?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password:
    druid:                  #德鲁伊连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 1000
      test-on-borrow: true
  servlet:
    multipart:
      max-file-size: 5MB          #上传文件的大小
#  security:
#    user:
#      name: admin
#      password: admin
#配置eureka(注册中心)
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${eureka.instance.ip-address}.${server.port}
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
#pojo包名(此项必须与jmyp-web-pojo项目中的包保持一致)
mybatis:
  type-aliases-package: com.czxy.jmyp.pojo
mapper:
  not-empty: false
  identity: mysql