server:
  port: 10010          #端口号


spring:
  application:
    name: api-web-gateway     #服务名
  servlet:
    multipart:
      max-file-size: 2MB       #上传文件的大小
#将网关服务添加到服务中心
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true


#网关的统一配置    访问路径：http://localhost:10010/v1/服务名/路径
zuul:
  prefix: /v1
  retryable: true
  routes:
    web-service: /web/**
#负载均衡全局配置
ribbon:
  ConnectTimeout: 100
  ReadTimeout: 600
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 2
  MaxAutoRetries: 1
#熔断的延时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000


sc:
  jwt:
    pubKeyPath: D:/rsa/rsa.pub # 公钥地址
  filter:
     allowPaths:
       - /login
       - /register

